// Single source of truth for service content. Consumed two ways:
//  1. lib/repositories/serviceRepository.ts reads this directly (no live DB
//     connected yet -- see docs/ARCHITECTURE.md).
//  2. prisma/seed.ts writes this same data into a real database once one
//     is connected, so the two paths never drift apart.
//
// This is the full, real service catalog and pricing taken directly from
// the business's own published price list (the source images shared at
// the start of this project) -- replacing the earlier placeholder catalog
// that approximated a handful of generic spa services.

export type ServiceCategory =
  | "FACIAL"
  | "FACIAL_ELECTRICAL"
  | "MASSAGE"
  | "BODY"
  | "WAXING"
  | "CHEMICAL_PEEL"
  | "SPECIALIZED"
  | "VAJACIAL"
  | "LASHES_BROWS"
  | "NAILS"
  | "MANICURE"
  | "PEDICURE"
  | "PACKAGE";

export interface ServiceTierSeed {
  name: string;
  priceCents: number;
  durationMinutes: number;
  description: string;
}

export interface ServiceSeed {
  id: string;
  slug: string;
  name: string;
  category: ServiceCategory;
  description: string;
  durationMinutes: number;
  priceCents: number;
  imageUrl: string;
  rating: number;
  isFeatured: boolean;
  tiers?: ServiceTierSeed[];
}

export const services: ServiceSeed[] = [
  // ---- Body plans / packages ----
  {
    id: "body-plan-6",
    slug: "body-plan-6-sessions",
    name: "Body Plan (6 Sessions)",
    category: "PACKAGE",
    description: "A combination of wood therapy, ice sculpting, lymph drainage, and cavitation across six sessions.",
    durationMinutes: 60,
    priceCents: 39000,
    imageUrl: "/assets/photos/sauna-relax.jpg",
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: "body-plan-8",
    slug: "body-plan-8-sessions",
    name: "Body Plan (8 Sessions)",
    category: "PACKAGE",
    description: "The full eight-session course of wood therapy, ice sculpting, lymph drainage, and cavitation.",
    durationMinutes: 60,
    priceCents: 52000,
    imageUrl: "/assets/photos/sauna-relax-2.jpg",
    rating: 4.8,
    isFeatured: false,
  },

  // ---- Body / wellness ----
  {
    id: "sauna-heat-therapy",
    slug: "sauna-heat-therapy",
    name: "Sauna Heat Therapy",
    category: "BODY",
    description: "Improves body and skin function through dry heat exposure.",
    durationMinutes: 30,
    priceCents: 4000,
    imageUrl: "/assets/photos/sauna-relax.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "body-polish",
    slug: "body-polish",
    name: "Body Polish",
    category: "BODY",
    description: "Full body scrub followed by a relaxing bath for soft, renewed skin.",
    durationMinutes: 60,
    priceCents: 5000,
    imageUrl: "/assets/photos/sauna-relax-2.jpg",
    rating: 4.7,
    isFeatured: false,
  },

  // ---- Massages ----
  {
    id: "essentials-soothing-massage",
    slug: "essentials-soothing-massage",
    name: "Essentials Soothing",
    category: "MASSAGE",
    description: "A gentle full-body massage designed to ease everyday tension and help you unwind.",
    durationMinutes: 60,
    priceCents: 6000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: "aroma-infused-massage",
    slug: "aroma-infused-massage",
    name: "Aroma Infused",
    category: "MASSAGE",
    description: "Full-body massage enhanced with essential oils to calm the mind and relax the body.",
    durationMinutes: 60,
    priceCents: 7000,
    imageUrl: "/assets/photos/oil-massage-candles.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "bamboo-massage",
    slug: "bamboo-massage",
    name: "Bamboo",
    category: "MASSAGE",
    description: "Warmed bamboo stalks are rolled and pressed into the muscles for deep, even relaxation.",
    durationMinutes: 60,
    priceCents: 7000,
    imageUrl: "/assets/photos/massage-table-orchid-3.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "mamas-prenatal-treat",
    slug: "mamas-prenatal-treat",
    name: "Mama's Prenatal Treat",
    category: "MASSAGE",
    description: "A gentle, pregnancy-safe massage to ease the aches that come with carrying.",
    durationMinutes: 60,
    priceCents: 7000,
    imageUrl: "/assets/photos/massage-table-orchid-4.jpg",
    rating: 4.9,
    isFeatured: false,
  },
  {
    id: "deep-muscle-reliever",
    slug: "deep-muscle-reliever",
    name: "Deep Muscle Reliever",
    category: "MASSAGE",
    description: "Firm, targeted pressure to release chronic tension in the muscles that hold it.",
    durationMinutes: 60,
    priceCents: 8000,
    imageUrl: "/assets/photos/massage-closeup-hands.jpg",
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: "heat-therapy-massage",
    slug: "heat-therapy-massage",
    name: "Heat Therapy",
    category: "MASSAGE",
    description: "Heat-assisted massage that loosens tight muscles before deeper work begins.",
    durationMinutes: 60,
    priceCents: 8000,
    imageUrl: "/assets/photos/hot-stone-massage.jpg",
    rating: 4.8,
    isFeatured: false,
  },
  {
    id: "back-neck-soothing",
    slug: "back-and-neck-soothing",
    name: "Back and Neck Soothing",
    category: "MASSAGE",
    description: "A focused massage for the back and neck, perfect for a quick reset.",
    durationMinutes: 30,
    priceCents: 3500,
    imageUrl: "/assets/photos/herbal-compress-massage.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "deep-back-neck",
    slug: "deep-back-and-neck",
    name: "Deep Back and Neck",
    category: "MASSAGE",
    description: "Firmer pressure focused on the back and neck for stubborn tension.",
    durationMinutes: 30,
    priceCents: 4500,
    imageUrl: "/assets/photos/herbal-compress-massage.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "scalp-neck-shoulder",
    slug: "scalp-neck-and-shoulder",
    name: "Scalp, Neck & Shoulder",
    category: "MASSAGE",
    description: "A short massage targeting the areas that carry the most everyday stress.",
    durationMinutes: 20,
    priceCents: 2500,
    imageUrl: "/assets/photos/massage-closeup-hands.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "lower-limbs-massage",
    slug: "lower-limbs-massage",
    name: "Lower Limbs",
    category: "MASSAGE",
    description: "A focused massage for tired legs and feet.",
    durationMinutes: 20,
    priceCents: 2500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "indian-crown-massage",
    slug: "indian-crown-massage",
    name: "Indian Crown",
    category: "MASSAGE",
    description: "A traditional scalp massage to relieve tension and promote relaxation.",
    durationMinutes: 20,
    priceCents: 2500,
    imageUrl: "/assets/photos/massage-table-orchid-5.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Vajacial ----
  {
    id: "vajacial",
    slug: "vajacial",
    name: "Vajacial",
    category: "VAJACIAL",
    description: "A gentle cleansing and exfoliating treatment for sensitive skin.",
    durationMinutes: 60,
    priceCents: 5000,
    imageUrl: "/assets/photos/lounge-chairs-juice.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "vaj-peel",
    slug: "vaj-peel",
    name: "Vaj Peel",
    category: "VAJACIAL",
    description: "A light chemical peel formulated for sensitive skin.",
    durationMinutes: 30,
    priceCents: 6000,
    imageUrl: "/assets/photos/lounge-chairs-juice.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "vaj-microneedling",
    slug: "vaj-microneedling",
    name: "Vaj Microneedling",
    category: "VAJACIAL",
    description: "Microneedling adapted for sensitive skin to support skin renewal.",
    durationMinutes: 60,
    priceCents: 6000,
    imageUrl: "/assets/photos/lounge-chairs-juice.jpg",
    rating: 4.5,
    isFeatured: false,
  },

  // ---- Lashes and brows ----
  {
    id: "eyebrow-shape-tint",
    slug: "eyebrow-shape-and-tint",
    name: "Eyebrow Shape & Tint",
    category: "LASHES_BROWS",
    description: "Brow shaping paired with a tint for a fuller, more defined look.",
    durationMinutes: 30,
    priceCents: 2000,
    imageUrl: "/assets/photos/cucumber-eye-mask.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "eyebrow-shape",
    slug: "eyebrow-shape",
    name: "Eyebrow Shape",
    category: "LASHES_BROWS",
    description: "Precision shaping to clean up and define your natural brow.",
    durationMinutes: 15,
    priceCents: 1000,
    imageUrl: "/assets/photos/cucumber-eye-mask.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "eyelash-tint",
    slug: "eyelash-tint",
    name: "Eyelash Tint",
    category: "LASHES_BROWS",
    description: "A semi-permanent tint to darken lashes without mascara.",
    durationMinutes: 20,
    priceCents: 1500,
    imageUrl: "/assets/photos/cucumber-eye-mask.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "eyebrow-tint",
    slug: "eyebrow-tint",
    name: "Eyebrow Tint",
    category: "LASHES_BROWS",
    description: "A semi-permanent tint to define and fill in brows.",
    durationMinutes: 20,
    priceCents: 1000,
    imageUrl: "/assets/photos/cucumber-eye-mask.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Waxing ----
  {
    id: "full-body-clean-up",
    slug: "full-body-clean-up-wax",
    name: "Full Body Clean-up",
    category: "WAXING",
    description: "Comprehensive full-body waxing in a single appointment.",
    durationMinutes: 120,
    priceCents: 12000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "full-intimate-wax",
    slug: "full-intimate-wax",
    name: "Full Intimate Wax",
    category: "WAXING",
    description: "Complete intimate waxing.",
    durationMinutes: 60,
    priceCents: 4500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "front-intimate-wax",
    slug: "front-intimate-wax",
    name: "Front Intimate Wax",
    category: "WAXING",
    description: "Intimate waxing, front area only.",
    durationMinutes: 45,
    priceCents: 3500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "intimate-line",
    slug: "intimate-line-wax",
    name: "Intimate Line",
    category: "WAXING",
    description: "A quick tidy-up along the intimate line.",
    durationMinutes: 25,
    priceCents: 2500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "full-leg-wax",
    slug: "full-leg-wax",
    name: "Full Leg Wax",
    category: "WAXING",
    description: "Smooth, long-lasting results for the entire leg.",
    durationMinutes: 45,
    priceCents: 4000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "three-quarter-leg-wax",
    slug: "three-quarter-leg-wax",
    name: "¾ Leg Wax",
    category: "WAXING",
    description: "Waxing from upper thigh to ankle.",
    durationMinutes: 30,
    priceCents: 3500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "half-leg-wax",
    slug: "half-leg-wax",
    name: "½ Leg Wax",
    category: "WAXING",
    description: "Waxing from knee to ankle, or knee to thigh.",
    durationMinutes: 30,
    priceCents: 3000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "full-arm-wax",
    slug: "full-arm-wax",
    name: "Full Arm Wax",
    category: "WAXING",
    description: "Smooth, even results from shoulder to wrist.",
    durationMinutes: 20,
    priceCents: 2500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "underarm-wax",
    slug: "underarm-wax",
    name: "Underarm Wax",
    category: "WAXING",
    description: "A quick, precise underarm wax.",
    durationMinutes: 15,
    priceCents: 1500,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "back-wax",
    slug: "back-wax",
    name: "Back Wax",
    category: "WAXING",
    description: "Full-back waxing for smooth, even results.",
    durationMinutes: 60,
    priceCents: 4000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "chest-wax",
    slug: "chest-wax",
    name: "Chest",
    category: "WAXING",
    description: "Chest waxing for smooth, even results.",
    durationMinutes: 30,
    priceCents: 3000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "stomach-wax",
    slug: "stomach-wax",
    name: "Stomach Wax",
    category: "WAXING",
    description: "A quick wax for the stomach area.",
    durationMinutes: 20,
    priceCents: 2000,
    imageUrl: "/assets/photos/massage-table-orchid.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "full-face-wax",
    slug: "full-face-wax",
    name: "Full Face Wax",
    category: "WAXING",
    description: "Gentle waxing for the full face.",
    durationMinutes: 45,
    priceCents: 3000,
    imageUrl: "/assets/photos/facial-massage-relax.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "nose-wax",
    slug: "nose-wax",
    name: "Nose Wax",
    category: "WAXING",
    description: "A quick nose wax.",
    durationMinutes: 10,
    priceCents: 500,
    imageUrl: "/assets/photos/facial-massage-relax.jpg",
    rating: 4.4,
    isFeatured: false,
  },
  {
    id: "chin-wax",
    slug: "chin-wax",
    name: "Chin Wax",
    category: "WAXING",
    description: "A quick chin wax.",
    durationMinutes: 10,
    priceCents: 500,
    imageUrl: "/assets/photos/facial-massage-relax.jpg",
    rating: 4.4,
    isFeatured: false,
  },

  // ---- Chemical peels: age prevention ----
  {
    id: "rice-bran-ao",
    slug: "rice-bran-ao-peel",
    name: "Rice Bran AO",
    category: "CHEMICAL_PEEL",
    description: "Treats early fine lines and wrinkles, improves uneven skin texture and color, and reduces sun spots.",
    durationMinutes: 30,
    priceCents: 5000,
    imageUrl: "/assets/photos/facial-mud-mask.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "lacti-firm-30-10",
    slug: "lacti-firm-30-10",
    name: "Lacti-Firm 30/10",
    category: "CHEMICAL_PEEL",
    description: "A lighter-strength lactic peel for smoother, brighter skin.",
    durationMinutes: 30,
    priceCents: 3000,
    imageUrl: "/assets/photos/facial-mud-mask-2.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "lacti-firm-90-10",
    slug: "lacti-firm-90-10",
    name: "Lacti-Firm 90/10",
    category: "CHEMICAL_PEEL",
    description: "Smoothens rough textured skin and brightens dullness.",
    durationMinutes: 30,
    priceCents: 4000,
    imageUrl: "/assets/photos/facial-mud-mask-3.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Chemical peels: age correction ----
  {
    id: "alpa-peel",
    slug: "alpa-peel",
    name: "Alpa Peel",
    category: "CHEMICAL_PEEL",
    description: "Increases collagen production and reduces fine lines and wrinkles.",
    durationMinutes: 30,
    priceCents: 4000,
    imageUrl: "/assets/photos/facial-mud-mask-4.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "retistore",
    slug: "retistore-peel",
    name: "Retistore",
    category: "CHEMICAL_PEEL",
    description: "A retinol-based peel to support age correction.",
    durationMinutes: 30,
    priceCents: 6000,
    imageUrl: "/assets/photos/facial-mud-mask-6.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "retistore-plus",
    slug: "retistore-plus-peel",
    name: "Retistore Plus",
    category: "CHEMICAL_PEEL",
    description: "Improves sun-damaged skin and hyperpigmentation, and slows down ageing.",
    durationMinutes: 30,
    priceCents: 7000,
    imageUrl: "/assets/photos/facial-mud-mask-cucumber.jpg",
    rating: 4.8,
    isFeatured: true,
  },

  // ---- Chemical peels: hyperpigmentation / congestion & acne ----
  {
    id: "beta-peel-retinol",
    slug: "beta-peel-with-retinol",
    name: "Beta Peel with Retinol",
    category: "CHEMICAL_PEEL",
    description: "Targets hyperpigmentation with a retinol-boosted beta peel.",
    durationMinutes: 30,
    priceCents: 6000,
    imageUrl: "/assets/photos/facial-mud-mask.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "beta-peel-plus",
    slug: "beta-peel-plus",
    name: "Beta Peel Plus",
    category: "CHEMICAL_PEEL",
    description: "A stronger beta peel for congestion and acne-prone skin.",
    durationMinutes: 60,
    priceCents: 5000,
    imageUrl: "/assets/photos/facial-mud-mask-2.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "azeac-peel",
    slug: "azeac-peel",
    name: "Azeac",
    category: "CHEMICAL_PEEL",
    description: "Attacks the bacteria that causes acne.",
    durationMinutes: 30,
    priceCents: 6000,
    imageUrl: "/assets/photos/facial-mud-mask-3.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Specialized treatments ----
  {
    id: "dermaplaning",
    slug: "dermaplaning",
    name: "Dermaplaning",
    category: "SPECIALIZED",
    description: "Gentle exfoliation that removes dead skin and fine vellus hair for smoother skin.",
    durationMinutes: 60,
    priceCents: 7000,
    imageUrl: "/assets/photos/facial-massage-outdoor.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "full-face-microneedling",
    slug: "full-face-microneedling",
    name: "Full Face Microneedling",
    category: "SPECIALIZED",
    description: "Stimulates collagen production across the full face for renewed skin.",
    durationMinutes: 90,
    priceCents: 10000,
    imageUrl: "/assets/photos/facial-massage-outdoor.jpg",
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: "half-face-microneedling",
    slug: "half-face-microneedling",
    name: "Half Face Microneedling",
    category: "SPECIALIZED",
    description: "A targeted microneedling treatment for specific areas of concern.",
    durationMinutes: 70,
    priceCents: 5000,
    imageUrl: "/assets/photos/facial-massage-outdoor.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Facials ----
  {
    id: "an-essentials-must",
    slug: "an-essentials-must",
    name: "An Essentials Must",
    category: "FACIAL",
    description: "Our signature facial — a complete treatment for healthy, radiant skin.",
    durationMinutes: 80,
    priceCents: 12000,
    imageUrl: "/assets/photos/facial-massage-relax.jpg",
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: "essentials-acne-attack",
    slug: "essentials-acne-attack",
    name: "Essentials Acne Attack",
    category: "FACIAL",
    description: "A deep-cleansing facial focused on clearing and calming acne-prone skin.",
    durationMinutes: 70,
    priceCents: 9000,
    imageUrl: "/assets/photos/facial-mud-mask.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "growth-factor-anti-ageing",
    slug: "growth-factor-anti-ageing",
    name: "Growth Factor Anti-Ageing",
    category: "FACIAL",
    description: "An advanced anti-ageing facial that supports the skin's natural renewal process.",
    durationMinutes: 60,
    priceCents: 9000,
    imageUrl: "/assets/photos/facial-mud-mask-2.jpg",
    rating: 4.8,
    isFeatured: true,
    tiers: [
      {
        name: "Essential",
        priceCents: 9000,
        durationMinutes: 60,
        description: "60-minute treatment with standard customization and professional-grade products.",
      },
      {
        name: "Premium",
        priceCents: 12500,
        durationMinutes: 75,
        description: "75-minute treatment with extended massage, premium products, and enhanced customization.",
      },
      {
        name: "Luxury",
        priceCents: 16000,
        durationMinutes: 90,
        description: "90-minute treatment with LED light therapy, luxury products, and take-home samples.",
      },
    ],
  },
  {
    id: "essentials-skin-quench",
    slug: "essentials-skin-quench",
    name: "Essentials Skin Quench",
    category: "FACIAL",
    description: "An intensely hydrating facial for skin that needs moisture back.",
    durationMinutes: 60,
    priceCents: 8500,
    imageUrl: "/assets/photos/facial-mud-mask-3.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "brightening-glow",
    slug: "brightening-glow-facial",
    name: "Brightening Glow",
    category: "FACIAL",
    description: "A radiance-boosting facial to even tone and restore glow.",
    durationMinutes: 60,
    priceCents: 8500,
    imageUrl: "/assets/photos/facial-mud-mask-4.jpg",
    rating: 4.7,
    isFeatured: false,
  },

  // ---- Facial electricals ----
  {
    id: "acne-attack-electrical",
    slug: "acne-attack-facial-electrical",
    name: "Acne Attack",
    category: "FACIAL_ELECTRICAL",
    description: "Galvanic dis-incrustation paired with direct high frequency to target acne.",
    durationMinutes: 20,
    priceCents: 4000,
    imageUrl: "/assets/photos/facial-mud-mask-6.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "hydrating-therapy-electrical",
    slug: "hydrating-therapy-facial-electrical",
    name: "Hydrating Therapy",
    category: "FACIAL_ELECTRICAL",
    description: "Galvanic iontophoresis paired with indirect high frequency for deep hydration.",
    durationMinutes: 20,
    priceCents: 4000,
    imageUrl: "/assets/photos/facial-mud-mask-cucumber.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "detox-facial-electrical",
    slug: "detox-facial-electrical",
    name: "Detox Facial",
    category: "FACIAL_ELECTRICAL",
    description: "Vacuum suction to detoxify and stimulate circulation.",
    durationMinutes: 10,
    priceCents: 3000,
    imageUrl: "/assets/photos/cucumber-eye-mask.jpg",
    rating: 4.4,
    isFeatured: false,
  },

  // ---- Artificial nails ----
  {
    id: "acrylic-natural-tips",
    slug: "acrylic-natural-tips",
    name: "Acrylic Natural Tips",
    category: "NAILS",
    description: "A natural-looking acrylic tip application.",
    durationMinutes: 60,
    priceCents: 3500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "acrylic-french-tips",
    slug: "acrylic-french-tips",
    name: "Acrylic French Tips",
    category: "NAILS",
    description: "Classic French tip acrylics.",
    durationMinutes: 60,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "acrylic-overlay-hard-gel",
    slug: "acrylic-overlay-hard-gel",
    name: "Acrylic Overlay / Hard Gel",
    category: "NAILS",
    description: "Strengthening overlay for natural nails.",
    durationMinutes: 60,
    priceCents: 3000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "sculptured-nails",
    slug: "sculptured-nails",
    name: "Sculptured Nails",
    category: "NAILS",
    description: "Fully sculpted nail extensions.",
    durationMinutes: 90,
    priceCents: 5000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "acrylic-overlay-gel",
    slug: "acrylic-overlay-plus-gel",
    name: "Acrylic Overlay + Gel",
    category: "NAILS",
    description: "Acrylic overlay finished with gel polish.",
    durationMinutes: 90,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "acrylic-backfill",
    slug: "acrylic-backfill",
    name: "Acrylic Backfill",
    category: "NAILS",
    description: "Maintenance fill for existing acrylics.",
    durationMinutes: 60,
    priceCents: 3000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "acrylic-backfill-gel",
    slug: "acrylic-backfill-plus-gel",
    name: "Acrylic Backfill + Gel",
    category: "NAILS",
    description: "Maintenance fill finished with gel polish.",
    durationMinutes: 60,
    priceCents: 3500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "nail-fix",
    slug: "nail-fix",
    name: "Nail Fix",
    category: "NAILS",
    description: "A quick repair for a single broken or damaged nail.",
    durationMinutes: 15,
    priceCents: 500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.4,
    isFeatured: false,
  },
  {
    id: "stick-ons-normal-polish",
    slug: "stick-ons-with-normal-polish",
    name: "Stick-ons with Normal Polish",
    category: "NAILS",
    description: "Press-on nails finished with standard polish.",
    durationMinutes: 60,
    priceCents: 2000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.4,
    isFeatured: false,
  },
  {
    id: "stick-ons-gel",
    slug: "stick-ons-with-gel",
    name: "Stick-ons with Gel",
    category: "NAILS",
    description: "Press-on nails finished with gel polish.",
    durationMinutes: 60,
    priceCents: 3500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "3d-nail-art",
    slug: "3d-nail-art",
    name: "3D Nail Art",
    category: "NAILS",
    description: "Decorative 3D nail art, priced per accent.",
    durationMinutes: 5,
    priceCents: 500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "nail-hardener-polish",
    slug: "nail-hardener-polish",
    name: "Nail Hardener Polish",
    category: "NAILS",
    description: "A strengthening polish treatment for weak or brittle nails.",
    durationMinutes: 30,
    priceCents: 1000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.4,
    isFeatured: false,
  },
  {
    id: "french-shellac-polish",
    slug: "french-shellac-polish",
    name: "French Shellac Polish",
    category: "NAILS",
    description: "Long-lasting French shellac polish application.",
    durationMinutes: 45,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "ombre-tips",
    slug: "ombre-tips",
    name: "Ombré Tips",
    category: "NAILS",
    description: "A gradient ombré tip finish.",
    durationMinutes: 75,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },

  // ---- Manicure / polish ----
  {
    id: "essentials-manicure",
    slug: "essentials-manicure",
    name: "Essentials Manicure",
    category: "MANICURE",
    description: "A classic manicure to clean, shape, and polish.",
    durationMinutes: 30,
    priceCents: 3000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "essentials-manicure-gel",
    slug: "essentials-manicure-plus-gel",
    name: "Essentials Manicure + Gel",
    category: "MANICURE",
    description: "Our classic manicure finished with long-lasting gel polish.",
    durationMinutes: 45,
    priceCents: 4500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "french-manicure",
    slug: "french-manicure",
    name: "French Manicure",
    category: "MANICURE",
    description: "A timeless French-tip manicure.",
    durationMinutes: 45,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "paraffin-manicure",
    slug: "paraffin-manicure",
    name: "Paraffin Manicure",
    category: "MANICURE",
    description: "A moisturizing paraffin wax treatment added to a full manicure.",
    durationMinutes: 60,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "cnd-shellac",
    slug: "cnd-shellac",
    name: "CND Shellac",
    category: "MANICURE",
    description: "Long-wear CND Shellac polish.",
    durationMinutes: 30,
    priceCents: 2500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "cnd-vinylux",
    slug: "cnd-vinylux-normal-polish",
    name: "CND Vinylux Normal Polish",
    category: "MANICURE",
    description: "Standard CND Vinylux polish application.",
    durationMinutes: 20,
    priceCents: 1000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.4,
    isFeatured: false,
  },

  // ---- Pedicures ----
  {
    id: "essentials-foot-works",
    slug: "essentials-foot-works",
    name: "Essentials Foot Works",
    category: "PEDICURE",
    description: "A refreshing pedicure to clean, shape, and soften.",
    durationMinutes: 45,
    priceCents: 3500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: true,
  },
  {
    id: "french-pedicure",
    slug: "french-pedicure",
    name: "French Pedicure",
    category: "PEDICURE",
    description: "A classic French-tip pedicure.",
    durationMinutes: 50,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "paraffin-pedicure",
    slug: "paraffin-pedicure",
    name: "Paraffin Pedicure",
    category: "PEDICURE",
    description: "A moisturizing paraffin wax treatment added to a full pedicure.",
    durationMinutes: 60,
    priceCents: 4000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "gel-pedicure",
    slug: "gel-pedicure",
    name: "Gel Pedicure",
    category: "PEDICURE",
    description: "A full pedicure finished with long-lasting gel polish.",
    durationMinutes: 60,
    priceCents: 5000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "acrylic-pedicure",
    slug: "acrylic-pedicure",
    name: "Acrylic Pedicure",
    category: "PEDICURE",
    description: "A pedicure with acrylic toenail application.",
    durationMinutes: 90,
    priceCents: 5000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "spalicious-foot-peel",
    slug: "spalicious-foot-peel",
    name: "Spalicious Foot Peel",
    category: "PEDICURE",
    description: "An intensive peeling treatment for soft, renewed feet.",
    durationMinutes: 120,
    priceCents: 6000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.8,
    isFeatured: false,
  },
  {
    id: "acrylic-toe-nails",
    slug: "acrylic-toe-nails",
    name: "Acrylic Toe Nails",
    category: "PEDICURE",
    description: "Acrylic application for toenails.",
    durationMinutes: 60,
    priceCents: 3000,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.5,
    isFeatured: false,
  },
  {
    id: "gel-paraffin-pedicure",
    slug: "gel-paraffin-pedicure",
    name: "Gel Paraffin Pedicure",
    category: "PEDICURE",
    description: "Paraffin treatment combined with a gel polish pedicure.",
    durationMinutes: 75,
    priceCents: 5500,
    imageUrl: "/assets/photos/foot-spa-frangipani.jpg",
    rating: 4.7,
    isFeatured: false,
  },
];

export interface AddOnSeed {
  id: string;
  name: string;
  priceCents: number;
}

export const addOns: AddOnSeed[] = [
  { id: "aromatherapy", name: "Aromatherapy Enhancement", priceCents: 2500 },
  { id: "hot-stones", name: "Hot Stone Therapy", priceCents: 3500 },
];
